################################################################################
# Copyright (c) 2021, NVIDIA CORPORATION. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
################################################################################

BaseConfig:
  minDetectorConfidence: 0.3
TargetManagement:
  enableBboxUnClipping: 1
  preserveStreamUpdateOrder: 0
  maxTargetsPerStream: 150
  minIouDiff4NewTarget: 0.50803391831819774
  minTrackerConfidence: 0.2379867160124702
  probationAge: 7
  maxShadowTrackingAge: 29
  earlyTerminationAge: 1
TrajectoryManagement:
  useUniqueID: 0
  enableReAssoc: 1
  minMatchingScore4Overall: 0.3491824364015243
  minTrackletMatchingScore: 0.3365923298667557
  minMatchingScore4ReidSimilarity: 0.21004668162204816
  matchingScoreWeight4TrackletSimilarity: 0.8531794819299393
  matchingScoreWeight4ReidSimilarity: 0.13580096342687126
  minTrajectoryLength4Projection: 33
  prepLength4TrajectoryProjection: 53
  trajectoryProjectionLength: 99
  maxAngle4TrackletMatching: 70
  minSpeedSimilarity4TrackletMatching: 0.03284195344815558
  minBboxSizeSimilarity4TrackletMatching: 0.20454200672158597
  maxTrackletMatchingTimeSearchRange: 24
  trajectoryProjectionProcessNoiseScale: 0.01
  trajectoryProjectionMeasurementNoiseScale: 100
  trackletSpacialSearchRegionScale: 0.1
  reidExtractionInterval: 0
DataAssociator:
  dataAssociatorType: 0
  associationMatcherType: 1
  checkClassMatch: 1
  minMatchingScore4Overall: 0.16498049370431805
  minMatchingScore4SizeSimilarity: 0.2470318611174308
  minMatchingScore4Iou: 0.09268843253527276
  minMatchingScore4VisualSimilarity: 0.3306397916012133
  matchingScoreWeight4VisualSimilarity: 0.2593903206246254
  matchingScoreWeight4SizeSimilarity: 0.6737211144111663
  matchingScoreWeight4Iou: 0.3538715510450657
  tentativeDetectorConfidence: 0.07696106106777956
  minMatchingScore4TentativeIou: 0.18259431931328785
StateEstimator:
  stateEstimatorType: 1
  processNoiseVar4Loc: 5500.457806079246
  processNoiseVar4Size: 2784.2546323956462
  processNoiseVar4Vel: 545.3315792468695
  measurementNoiseVar4Detector: 100.00000497224985
  measurementNoiseVar4Tracker: 294.4755412477389
VisualTracker:
  visualTrackerType: 1
  useColorNames: 1
  useHog: 1
  featureImgSizeLevel: 5
  featureFocusOffsetFactor_y: -0.21492658069764317
  filterLr: 0.04747373772798158
  filterChannelWeightsLr: 0.06898637782721721
  gaussianSigma: 0.7195646880047487
ReID:
  reidType: 0
  outputReidTensor: 0
  batchSize: 100
  workspaceSize: 1000
  reidFeatureSize: 256
  reidHistorySize: 250
  inferDims: [3, 256, 128]
  networkMode: 1
  inputOrder: 0
  colorFormat: 0
  offsets: [123.6750, 116.2800, 103.5300]
  netScaleFactor: 0.01735207
  keepAspc: 1
  addFeatureNormalization: 1
  tltModelKey: nvidia_tao
  tltEncodedModel: ../models/resnet50_market1501_aicity156.onnx
  modelEngineFile: ../models/resnet50_market1501_aicity156.onnx_b100_gpu0_fp16.engine
